### ISSUE TITLE
Explain signing

### ISSUE THREAD

**Issue by fulldecent** [pierredavidbelanger/githubappcaster#1]
Please explain how appcast signing works with this tool.

**Comment by pierredavidbelanger** [comment]
This project is not responsible to sign anything.

Please see the [README](https://github.com/pierredavidbelanger/githubappcaster#github-app-caster).

Simply put: Its a web application that take [GitHub project's releases infos](https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository) and publish them as a [Sparkle compatible appcast RSS feed](https://sparkle-project.org/files/sparkletestcast.xml).

So, you will need to understand points 0 to 3 from the [Sparkle documentation](https://sparkle-project.org/documentation/) before [using this project](https://github.com/pierredavidbelanger/githubappcaster#deploy-the-server-side-application).

**Comment by fulldecent** [comment]
The Sparkle compatible appcast uses `sparkle:dsaSignature`. Does githubappcaster get that directly from GitHub releases?

**Comment by pierredavidbelanger** [comment]
Ok, I see what you mean :)

Indeed this project does not support the optional `sparkle:dsaSignature` attribute.

If you want to protect your users from corruption and man-in-the-middle attacks, you can sign your app with an [Apple Developer ID](https://developer.apple.com/developer-id/). It will have the same effect as the `sparkle:dsaSignature` attribute. And also, the users are kind of expecting this anyways, because if you does not sign your app, they will see an annoying OS X security popup when they open your app.

**Comment by fulldecent** [comment]
Got it: so I just sign my apps as normal and use this then everything works great. Thanks!
